function ser = serial_open(cfg)
%SERIAL_OPEN Open the configured low-latency serial port.
try
    ser = serialport(cfg.serial.port, cfg.serial.baudrate, ...
        "DataBits", cfg.serial.data_bits, ...
        "Parity", char(cfg.serial.parity), ...
        "StopBits", cfg.serial.stop_bits, ...
        "Timeout", cfg.serial.timeout);
    flush(ser);
catch ME
    error("serial_open:OpenFailed", ...
        "Failed to open %s @ %d baud: %s", ...
        cfg.serial.port, cfg.serial.baudrate, ME.message);
end
end
